### ISSUE TITLE
Problem with dumping.

### ISSUE THREAD

**Issue by Dziksonn** [marcodsl/FiveM-Client-Dumper#2]
When i'm trying to use your program i got error
"N├úo foi poss├şvel prosseguir com a aplica├ž├úo: O arquivo de sa├şda n├úo ├ę um diret├│rio." any ideas?
If it is easier for you to explain it on discord
Dziksonn#4368

**Comment by Dziksonn** [comment]
Nvm, my bad

**Comment by marcodsl** [comment]
Thanks for reporting! I'm glad you could fix it on your own.

In general, you get this error when the output file is not a directory. Is that what happened in your case? It would be great if you could share what you did in order to help other people who may have the same issue in the future.
