### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by EgeTurker** [marcodsl/FiveM-Client-Dumper#3]
Hello, thanks for this nice content. What is changed in version 1.0.2 and do you think about release it?

**Comment by EgeTurker** [comment]
EDIT: Only "CFX Root UI" is visible on CEF remote debugging and when I try to dump any server, It gives an error.

**Comment by marcodsl** [comment]
Hi! Version 1.0.2 contains bugfixes and minor code improvements. It's already avaliable an you can download it [here](https://github.com/marcodsl/FiveM-Client-Dumper/releases/tag/1.0.2). The error you mentioned is one of those which has been fixed.

Thank you for your feedback!
