### ISSUE TITLE
Suggestion and Issue!

### ISSUE THREAD

**Issue by Lywenw** [marcodsl/FiveM-Client-Dumper#4]
Hello, I know this is not Issue, sorry. But I have a suggestion. You will make a tool which we can get a currently connected server's real ip and port. Thank you, have a nice day.

**Comment by Lywenw** [comment]
Issue: If the __resource.lua's files {} part writed like 'html/static/img/*.png' (not 'html/static/img/x.png') (If they use * as writing all image files.) its not dumping.

**Comment by marcodsl** [comment]
Hey! You can use `netstat -a` to check all your current connections.

About the issue you reported, there's no much I can do, since the only way I can tell the program which files it has to fetch is by parsing the manifest file (`__resource.lua`/`fxmanifest.lua`).
