### ISSUE TITLE
_Collection is empty

### ISSUE THREAD

**Issue by MrTurtles** [marcodsl/FiveM-Client-Dumper#6]
Hi, I am getting an error named with the following statement: 
_Collection is empty

IF you need the whole error I'd like to share it with you on discord DaveK#0001 or by image here.

**Comment by MrTurtles** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/27373644/84825956-8847b980-b022-11ea-91e9-cf628bdd1b57.png)

**Comment by marcodsl** [comment]
https://github.com/marcodsl/FiveM-Client-Dumper/commit/261d538d894b10c2cf47715961f7188e20687fbf
